sudo: false

language: scala

scala:
  - 2.11.8
  - 2.12.0

jdk:
  - oraclejdk8

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

script:
  - sbt -sbt-version 0.13.13 -scala-version $TRAVIS_SCALA_VERSION ';clean; testOnly -- xonly'
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
